tableone.py
test_tableone.py

e.g. if doing chi2, and one of the cell counts is 0, the test returns a value error (example below)
```python
/usr/local/lib/python2.7/dist-packages/tableone.pyc in __init__(self, data, continuous, categorical, strata_col, nonnormal, pval)
60         # forgive me jraffa
61         if strata_col:
---> 62             self._significance_table = self.__create_significance_table(data)
63 
64         self._n_row = self.__create_n_row(data)
/usr/local/lib/python2.7/dist-packages/tableone.pyc in __create_significance_table(self, data)
213             df.loc[v]['min_n'] = len(min(grouped_data,key=len))
214             # compute p value
--> 215             df.loc[v]['pval'],df.loc[v]['testname'] = self.__p_test(df,v,grouped_data,data)
216 
217         return df …
```

fix stat testing for categorical variables

---

tableone.py
test_tableone.py

This speeds up the _cat_describe function ~10-40 times or so by using the levels as an index in the dataframe

Speed up _cat_describe

---

tableone.py
test_tableone.py

Changes
* coerces data types to numeric if they were not specified as categorical
* raises a warning if all the data in a numeric column are coerced to null
* minor fixes and additional tests

Continuous describe can now handle mixed datatypes

---

setup.py
tableone.py
test_tableone.py

Allow the user to specify a statistical test. e.g.
```
from tableone import TableOne
from scipy import stats
import numpy as np
import pandas as pd
```
```
np.random.seed(12345678)
n1 = 200
n2 = 300
rvs1 = stats.norm.rvs(size=n1, loc=0., scale=1)
rvs2 = stats.norm.rvs(size=n2, loc=0.5, scale=1.5)
df1 = pd.DataFrame({'rvs': 'rvs1', 'val': rvs1})
df2 = pd.DataFrame({'rvs': 'rvs2', 'val': rvs2})
different = df1.append(df2)
```
```
def mytest(*args):
mytest.__name__ = "BOING"
_, pval= stats.ks_2samp(*args)
return pval
```
```
t1_diff = TableOne(data=different, columns = ["val"], pval=True,
groupby="rvs", pval_test={"val": mytest})
print(t1_diff._significance_table['P-Value'].val)
print(stats.ks_2samp(rvs1, rvs2)))
```

support user defined tests. ref #92

---

tableone/tableone.py

Minor change to the documentation:
```
The P-values from the unadjusted table (default when pval=True)
are adjusted to account for the number of total tests that were performed.
These adjustments would be useful when many variables are being screened
to assess if their distribution varies by the variable in the groupby argument.
```

change pval_adj docs

---

docs/bestpractice.rst
docs/contributing.rst
tableone/modality.py

Corrects some typos in the repository.

Correct some typos

---

README.md

The current list of Anaconda badges is at: https://anaconda.org/conda-forge/tableone/badges/
It looks like the previous badge was discontinued. This pull request updates the badge to point to the new location.

Fix anaconda badge

---

requirements.txt
setup.py

As discussed in https://github.com/tompollard/tableone/issues/122, trying to use `TableOne.to_excel()` raises an error: `ModuleNotFoundError: No module named 'openpyxl'`
This pull request adds openpyxl as a dependency, meaning that people should no longer see the error when calling `.to_excel()`

Add openpyxl as a dependency. Fixes #122.

---

requirements.txt
setup.py
tableone/tableone.py

This is a slightly random collection of changes:
- Bump scipy, statsmodels, and tabulate.
- Minor tidying and adding typehints (lots more work needed!)

Minor formatting changes (typehints)

---

.flake8
.github/workflows/python-package.yml

The default max width of 79 characters is limiting. Bump to 119 characters in a new `.flake8` configuration file.

Increase max width to 119 characters for Flake8 style check

---

pyproject.toml

This pull request adds a [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) file with basic build requirements. setup.py can be removed in a later pull request, assuming `pyproject.toml` is configured correctly.

Add pyproject.toml to replace setup.py

---

tableone/tableone.py

As discussed in https://github.com/tompollard/tableone/pull/153, it would be good to have type checks to the GitHub workflow. Right now, there are a lot of typing issues being reported by pyright.
I think it's best to begin by adding `# type: ignore` comments initially. That is what is happening in this PR.
We can then work on removing these comments and fixing the typing issues.

Ignore typing errors for now. Remove the "type: ignore" comments later!

---

tableone/tableone.py

In https://github.com/tompollard/tableone/issues/138, @davidkurland asks whether we could highlight P-Values that fall below a threshold.
This pull request adds a `pval_threshold` argument. When set (e.g. `pval_threshold = 0.01`), we display an asterisk (`*`) after all p-values that fall below this threshold.
e.g.
```
from tableone import TableOne, load_dataset
data = load_dataset('pn2012')
table1 = TableOne(data, groupby="death", pval=True, pval_threshold=0.2)
print(table1.tabulate(tablefmt = "github"))
```
Displays:
|                   |      | Missing   | Overall      | 0            | 1            | P-Value   |
|-------------------|------|-----------|--------------|--------------|--------------|-----------|
| n                 |      |           | 1000         | 864          | 136 …

WIP: Display asterisk next to P-Value when it is below a defined threshold

---

tableone/tableone.py
tests/unit/test_tableone.py

Minor changes to update syntax to address warnings raised when running pytest with Pandas v2.2.2:
```
⏚ [tompollard:~/projects/tableone] [env] main* 5s ± pytest
======================================= test session starts ========================================
platform darwin -- Python 3.9.19, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/tompollard/projects/tableone
collected 30 items                                                                                 
tests/unit/test_tableone.py ..............................                                   [100%]
========================================= warnings summary =========================================
tests/unit/test_tableone.py: 36 warnings
/Users/tompollard/projects/tableone/tableone/tableone.py:929: FutureWarning: The provided …
```

Fix deprecated Pandas syntax (up to v2.2.2)

---

tableone/tableone.py
tests/unit/test_tableone.py

This pull request moves some of the content from __init__ into the following methods:
- `_handle_deprecations`: reports on deprecated arguments
- `_validate_arguments`: runs checks on the input arguments
- `_validate_data`: runs checks on the input dataframe
In addition, support for the following arguments has been dropped: `labels`, `isnull`, `pval_test_name`, `remarks`.

Refactoring for readability: Add _handle_deprecations, _validate_arguments, _validate_data methods.

---

tableone/tableone.py
tableone/validators.py
tests/unit/test_tableone.py

Refactoring for readability. This pull request moves code for validating input data and arguments to a new "validators.py" module. 
validators.py has two classes:
- `DataValidator`: code for checking the dataset
- `InputValidator`: code for checking the arguments (should I have called this something like `ArgumentValidator`?)
The old validation code did some type manipulation (e.g. if groupby was provided as a list, it would be silently converted to a str). I have removed this code for now, and will work out what to do with it later.

Move validation code to a new validators.py module

---

tableone/statistics.py
tableone/tableone.py

Refactoring for readability. 
This pull request moves code for statistical tests into a new "statistics.py" module.
statistics.py has a single `Statistics` classes that contains code for running all statistical tests used by TableOne.

Move statistical code to a new statistics.py module

---

README.md
tableone/deprecations.py
tableone/tableone.py

Refactoring for readability.
This pull request moves code for deprecating parameters and functions into a new "deprecations.py" module.

Move handling of deprecated parameters to deprecations module.

---

.github/workflows/python-package.yml

Currently the GitHub "[python-package.yml](https://github.com/tompollard/tableone/blob/main/.github/workflows/python-package.yml)" workflow is getting piped into a coverage report. As a result, if tests fail pytest is not returning an error code. This pull request ensures that failed tests are clearly reported in GitHub (and removes coverage in the process).

Remove coverage. Ensure pytest returns failure code on fail.

---

tableone/preprocessors.py
tableone/tableone.py
tableone/tables.py
tableone/validators.py
tests/unit/test_tableone.py

Adds a new `include_null` argument. If set to True, null values for categorical values will be treated as a category level:
```
include_null : bool, optional
Include None/Null values for categorical variables by treating them as a
category level. (default: True)
```
This fixes the issue described in https://github.com/tompollard/tableone/issues/114.

Add include_null argument to handle nulls for categorical values. Ref #114.

---

tableone/preprocessors.py
tests/unit/test_tableone.py

As highlighted in #177, setting `include_null = True` will fail for categorical data types (i.e. if a column has been converted to the Pandas Categorical type, `include_null=True` will raise an error).
After applying this fix, the following code should add the "None" category as expected:
```
import tableone
import pandas as pd
dummy_table = pd.DataFrame(
{
"age": [70, 80, 90, 85, 99],
"sex": ["m", "f", "m", "f", None]
}
)
dummy_table["sex"] = dummy_table["sex"].astype("category")
tableone.TableOne(dummy_table)
```
Returns:
|                |      | Missing   | Overall     |
|----------------|------|-----------|-------------|
| n              |      |           | 5           |
| age, mean (SD) |      | 0         | 84.8 (10.8) |
| sex, n (%)     | None |           | 1 (20.0)    |
| …

TableOne with categorical pandas DataFrame column raises TypeError

---

requirements.txt

Bump scipy from 1.10.1 to 1.13.1.

Bump scipy from 1.10.1 to 1.13.1.

---

tableone/tables.py
tests/unit/test_tableone.py

As discussed in https://github.com/tompollard/tableone/issues/182, there was an issue with summary tables that were created when a level of a categorical variable was missing in one of the "group by" groups. This led to two main problems:
- Inconsistent indexing across groups, which broke alignment during standardized mean difference (SMD) computation.
- Dropped rows for category levels that existed in the full dataset, but were absent in some groups.
This pull request resolves issue #182 by ensuring that categorical variables are included in the summary table even when they are not present within a grouping.

Fix creation of categorical tables when missing category levels

---

tableone/preprocessors.py
tableone/tableone.py
tests/unit/test_tableone.py

This PR fixes a `TypeError` that occurs when computing p-values for categorical variables containing missing values. The error arises because missing values are replaced with the string 'None', leading to mixed-type categories (e.g.`int` and `str`) which cannot be sorted during internal processing (ref #161 and #160).
Previously, the following code would raise `TypeError: '<' not supported between instances of 'str' and 'int'`:
```
from tableone import TableOne
import pandas as pd
import numpy as np
df = pd.DataFrame({
'group': ['A', 'B', 'A', 'B', 'A'],
'numeric_cat': [1, 2, np.nan, 2, 1]
})
t1 = TableOne(df, columns=['numeric_cat'], categorical=['numeric_cat'], groupby='group', pval=True)
print(t1.tableone)
```
The fixes are:
- Modified `handle_categorical_nulls()` to convert entire …

Fix TypeError when computing p-values with missing categorical values

---

tableone/formatting.py
tableone/tableone.py
tests/unit/test_tableone.py

This pull request addresses the following request in #189 
> Feature request:
> It would be great to have a pDigits argument to control the number of decimal places shown for p-values in the summary table.
Setting the `pval_digits` argument allows the user to specify the precision of the p-value (number of decimal places).
The pull request also adds the missing `pval_threshold` argument from the docstring (fixes #190)

Add pval_digits argument.

---

tableone/statistics.py
tableone/tableone.py
tableone/tables.py
tests/unit/test_tableone.py

This pull request introduces a new `ttest_equal_var` argument to the TableOne class, allowing users to specify whether equal variances should be assumed when performing t-tests (see: https://github.com/tompollard/tableone/issues/193).
By default `ttest_equal_var=False`, which performs Welch’s t-test, a test that does not assume equal variance between groups.
```
df = pd.DataFrame({
'group': ['A', 'A', 'A', 'B', 'B', 'B'],
'x': [1.0, 2.0, 3.0, 20.0, 22.0, 24.0]
})
```
```
t1 = TableOne(df, columns=['x'], groupby='group', pval=True, ttest_equal_var=False, pval_digits=5)
pval_welch = t1.tableone[('Grouped by group', 'P-Value')].iloc[1]
```
```
t2 = TableOne(df, columns=['x'], groupby='group', pval=True, ttest_equal_var=True, pval_digits=5)
pval = t2.tableone[('Grouped by group', …
```

Add ttest_equal_var argument to control t-test variance assumption

---

.github/workflows/python-package.yml
tableone.ipynb
tableone/formatting.py
tableone/tableone.py
tests/test_histograms.py

This pull request adds two new arguments to address #132:
```
show_histograms : bool, default=False
Whether to include mini-histograms for continuous variables.
clip_histograms : tuple or None, default (1, 99)
If show_histograms=True, specify a (lower_percentile, upper_percentile) range to clip the
data before generating histograms. This reduces the influence of extreme outliers.
For example, (1, 99) clips to the 1st and 99th percentiles.
Set to None to disable clipping and use the full range of values.
```
When show_histograms is set to True, histograms will be added at the end of the table. A simple example is shown below:
```
from tableone import TableOne, load_dataset
data = load_dataset('pn2012')
table1 = TableOne(data, show_histograms=True) …
```

Add `show_histograms` argument to display histograms (and `clip_histograms` for clipping outliers).
